<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;
use Carbon\Carbon;

class DataPelangganSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('data_pelanggans')->insert([
            [
                'kode' => 'PLG001',
                'nama' => 'Ahmad Setiawan',
                'noHP' => '081234567890',
                'password' => Hash::make('password123'),
                'alamat' => 'Jl. Merdeka No. 10, Yogyakarta',
                'keluhan' => 'Motor listrik tidak bisa menyala',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'kode' => 'PLG002',
                'nama' => 'Rina Kusuma',
                'noHP' => '082345678901',
                'password' => Hash::make('rinasecret'),
                'alamat' => 'Jl. Kaliurang Km 5, Sleman',
                'keluhan' => 'Baterai cepat habis',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'kode' => 'PLG003',
                'nama' => 'Budi Santoso',
                'noHP' => '083456789012',
                'password' => Hash::make('budikuat'),
                'alamat' => 'Jl. Parangtritis No. 22, Bantul',
                'keluhan' => 'Lampu indikator rusak',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'kode' => 'PLG004',
                'nama' => 'Siti Aminah',
                'noHP' => '084567890123',
                'password' => Hash::make('siti2024'),
                'alamat' => 'Jl. Malioboro No. 5, Yogyakarta',
                'keluhan' => 'Rem belakang tidak berfungsi',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'kode' => 'PLG005',
                'nama' => 'Joko Widodo',
                'noHP' => '085678901234',
                'password' => Hash::make('jokopass'),
                'alamat' => 'Jl. Adi Sucipto No. 3, Sleman',
                'keluhan' => 'Motor mati saat hujan',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'kode' => 'PLG006',
                'nama' => 'Indah Permata',
                'noHP' => '086789012345',
                'password' => Hash::make('indahpass'),
                'alamat' => 'Jl. Gejayan No. 12, Yogyakarta',
                'keluhan' => 'Layar digital error',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'kode' => 'PLG007',
                'nama' => 'Agus Riyanto',
                'noHP' => '087890123456',
                'password' => Hash::make('agus123'),
                'alamat' => 'Jl. Solo Km 9, Kalasan',
                'keluhan' => 'Stang terasa berat',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'kode' => 'PLG008',
                'nama' => 'Dewi Sartika',
                'noHP' => '088901234567',
                'password' => Hash::make('dewikuat'),
                'alamat' => 'Jl. Wates No. 18, Kulon Progo',
                'keluhan' => 'Motor bergetar saat jalan',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'kode' => 'PLG009',
                'nama' => 'Fajar Hidayat',
                'noHP' => '089012345678',
                'password' => Hash::make('fajar321'),
                'alamat' => 'Jl. Godean No. 27, Sleman',
                'keluhan' => 'Pengisian baterai lambat',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'kode' => 'PLG010',
                'nama' => 'Nina Zulaikha',
                'noHP' => '081122334455',
                'password' => Hash::make('ninakuat'),
                'alamat' => 'Jl. Babarsari No. 11, Yogyakarta',
                'keluhan' => 'Suara motor terlalu keras',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'kode' => 'PLG011',
                'nama' => 'Yoga Prasetya',
                'noHP' => '082233445566',
                'password' => Hash::make('yogapass'),
                'alamat' => 'Jl. Ringroad Selatan, Bantul',
                'keluhan' => 'Gas motor tidak responsif',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'kode' => 'PLG012',
                'nama' => 'Sari Puspita',
                'noHP' => '083344556677',
                'password' => Hash::make('sarikuat'),
                'alamat' => 'Jl. Palagan Tentara Pelajar, Sleman',
                'keluhan' => 'Motor tidak bisa mundur',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'kode' => 'PLG013',
                'nama' => 'Taufik Hidayat',
                'noHP' => '084455667788',
                'password' => Hash::make('taufik123'),
                'alamat' => 'Jl. Timoho No. 4, Yogyakarta',
                'keluhan' => 'Ban sering kempes',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'kode' => 'PLG014',
                'nama' => 'Lisa Maulida',
                'noHP' => '085566778899',
                'password' => Hash::make('lisasecret'),
                'alamat' => 'Jl. Kusumanegara, Kota Yogyakarta',
                'keluhan' => 'Motor mengeluarkan bau aneh',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'kode' => 'PLG015',
                'nama' => 'Arif Nugroho',
                'noHP' => '086677889900',
                'password' => Hash::make('arifpass'),
                'alamat' => 'Jl. Janti, Sleman',
                'keluhan' => 'Speedometer tidak akurat',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'kode' => 'PLG016',
                'nama' => 'Mega Dwi',
                'noHP' => '087788990011',
                'password' => Hash::make('megapass'),
                'alamat' => 'Jl. Wonosari Km 7, Gunungkidul',
                'keluhan' => 'Charger rusak',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'kode' => 'PLG017',
                'nama' => 'Rizki Amelia',
                'noHP' => '088899001122',
                'password' => Hash::make('rizkikuat'),
                'alamat' => 'Jl. Kali Code, Yogyakarta',
                'keluhan' => 'Motor sering mati sendiri',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'kode' => 'PLG018',
                'nama' => 'Doni Wahyudi',
                'noHP' => '089900112233',
                'password' => Hash::make('donikuat'),
                'alamat' => 'Jl. Cendrawasih No. 6, Sleman',
                'keluhan' => 'Kunci motor macet',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'kode' => 'PLG019',
                'nama' => 'Yuni Astuti',
                'noHP' => '081133224455',
                'password' => Hash::make('yunipass'),
                'alamat' => 'Jl. Solo Km 7, Kalasan',
                'keluhan' => 'Tidak bisa konek ke aplikasi',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'kode' => 'PLG020',
                'nama' => 'Anton Subagyo',
                'noHP' => '082144556677',
                'password' => Hash::make('anton123'),
                'alamat' => 'Jl. Cokroaminoto No. 15, Sleman',
                'keluhan' => 'Motor tersendat saat akselerasi',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
        ]);
    }
}
